image: Visual Studio 2019
skip_commits:
  message: /doco|Merge pull request.*/
build_script:
- ps: >-
    dotnet build src --configuration Release

    appveyor PushArtifact \**\*received.*

    dotnet test src --configuration Release --no-build --no-restore
test: off
artifacts:
- path: \**\*received.*